### ISSUE TITLE
threshold for classifier

### ISSUE THREAD

**Issue by rxjx** [autogluon/autogluon#1038]
Is there a way to get the threshold for a trained classifier, i.e. to convert predict_proba returned values to binary (or multi-class) predictions? I can't find anything in the docs or in the issues for this. I'd rather not fork and modify the code if possible.

**Comment by Innixma** [comment]
Currently it is always 0.5 for binary or the max for multiclass. We don't adjust thresholds when making predictions.

**Comment by jwmueller** [comment]
If you would like to use a different threshold, please use `predict_proba()` and then apply your own threshold to decide how to map these predicted class-probabilities into predicted class-labels.

**Comment by rxjx** [comment]
Yes, I was already doing that. I was just curious if that gets adjusted internally as part of optimization. Is it not done because you've seen that causing overfitting? Or is there a theoretical ERM reason not to? I assume you're not doing it because you don't know the cost of misclassification for each category.

**Comment by jwmueller** [comment]
@rxjx  I think we just haven't adjusted threshold internally simply due to lack of bandwidth :) 
If you'd like to help contribute this, that would be awesome!

The steps needed would be something like:

1) add optional `class_threshold` argument to `predict()` function. Make sure `class_threshold` can also take in array & pd.Series of thresholds for each class in multiclass classification (and include check to ensure these thresholds are actually realizable for multiclass such that one of the classes will always be predicted for every row).

2) automatically set this `class_threshold` argument based on `eval_metric` for only those evaluation-metrics that depend on `predict()` rather than `predict_proba()`. For example: `accuracy`, `balanced_accuracy`, `f1_score`, etc.

See possible metrics in: 
https://github.com/awslabs/autogluon/blob/master/core/src/autogluon/core/metrics/__init__.py
https://github.com/awslabs/autogluon/blob/master/core/src/autogluon/core/metrics/classification_metrics.py

Note that for many metrics, a reasonable `class_threshold` to use can simply be hard-coded (Eg: = 0.5 for binary classification accuracy, = class frequency for balanced_accuracy, etc), so I'd start with that before trying to iteratively optimize the threshold based on computed validation-scores.

**Comment by rxjx** [comment]
Thanks for the response. I can definitely take a look at doing this, although not in a prompt manner since work and another side project claim time. Might be nice to return confusion matrices for some thresholds too or perhaps graphical representations.

**Comment by jwmueller** [comment]
Awesome to hear you're interested 👍 
I agree graphical representations would be nice to show, note that we do already offer confusion-matrix functionality inside our `evaluate_predictions()` function.

You can also email us at: autogluon-dev@amazon.com
for private Qs or to receive an invite to our Slack channel for contributors.

**Comment by rxjx** [comment]
I think the multiclass case gets complicated fast. Let's restrict it to binary for the first pass?

**Comment by jwmueller** [comment]
Yes I think an initial PR can just add it this functionality for only binary classification since it's more straightforward and the most common use-case. For other problem-types you could for now simply print error message if the user has specified the optional threshold argument.

**Comment by mirix** [comment]
Hello, has this functionality been implemented? It would be very useful.

**Comment by rxjx** [comment]
Sorry, haven't found time to work on it at all. Work has been overloaded and the advent of LLMs has added to the load. Realistically, it doesn't look like I can get to it anytime soon.
