### ISSUE TITLE
TabularPredictor redirect verbose output to file

### ISSUE THREAD

**Issue by tonywavicle** [autogluon/autogluon#2325]
Hi, how do I redirect the verbose output from the terminal when I execute the TabularPredictor command to a file?

example:
When I run the following command below
`predictor = TabularPredictor(xxxx).fit(train_data)`

I would like the output from the training to go to a file instead of the terminal. 

I have tried this method but it does not work:
```
from contextlib import redirect_stdout
with open('out.txt', 'w') as f:
    with redirect_stdout(f):
        predictor = TabularPredictor(xxxx).fit(train_data)
```

And this method does not work either
```
import sys
with open('out.txt', 'w') as sys.stdout:
    predictor = TabularPredictor(xxxx).fit(train_data)
```

**Comment by Innixma** [comment]
Great question! It is indeed puzzling.

@yinweisu This might be related to how I suspect we are sending to stderr instead of stdout for our logging, but also appears that `redirect_stderr` doesn't work out of the box either.

**Comment by Innixma** [comment]
This works:

```python3

import sys

with open('out.txt', 'w') as sys.stderr:
    from autogluon.tabular import TabularPredictor, TabularDataset
    train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
    test_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')
    predictor = TabularPredictor(label='class').fit(train_data=train_data)
    predictions = predictor.predict(test_data)

```

But this does not:

```python3

import sys
from autogluon.tabular import TabularPredictor
with open('out.txt', 'w') as sys.stderr:
    from autogluon.tabular import TabularDataset
    train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
    test_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')
    predictor = TabularPredictor(label='class').fit(train_data=train_data)
    predictions = predictor.predict(test_data)

```

Simplifying:

```python3
import sys
import autogluon.core
with open('out.txt', 'w') as sys.stderr:
    import logging
    ag_logger = logging.getLogger('autogluon')

    logging.log(30, 'Test 1')  # This is saved to file
    ag_logger.log(30, 'Test 2')  # This is printed

```

Simplifying:

```python3
import sys
import autogluon.common
with open('out.txt', 'w') as sys.stderr:
    import logging
    ag_logger = logging.getLogger('autogluon')

    logging.log(30, 'Test 1')  # This is saved to file
    ag_logger.log(30, 'Test 2')  # This is saved to file

```

Found function causing issue:

```python3
import sys
from autogluon.common.utils.log_utils import _add_stream_handler
_add_stream_handler()
with open('out.txt', 'w') as sys.stderr:
    import logging
    ag_logger = logging.getLogger('autogluon')

    logging.log(30, 'Test 1')  # This is saved to file
    ag_logger.log(30, 'Test 2')  # This is printed

```

Caused by:

```python3

def _add_stream_handler():
    # Add stream_handler to AG logger if it doesn't already exist
    # This is necessary so that the modification of logging level can take effect
    # Also this adjust the logging format
    # This function is supposed to be called before any logging from autogluon happens
    if not any(isinstance(h, logging.StreamHandler) for h in _logger_ag.handlers):
        stream_handler = logging.StreamHandler()
        formatter = logging.Formatter('%(message)s')
        stream_handler.setFormatter(formatter)
        _logger_ag.addHandler(stream_handler)  # <--------------- This line causes the log to be printed 
        _logger_ag.propagate = False
```

**Comment by Innixma** [comment]
Solution: have your `with` statement occur before importing AutoGluon + use stderr and it should work fine for now.

**Comment by yinweisu** [comment]
So I've played around with it a little bit, and found this:
```python
from autogluon.common.utils.log_utils import _add_stream_handler
import logging
import sys

logger = logging.getLogger(__name__)
ag_logger = logging.getLogger('autogluon')

with open('out.txt', 'w') as sys.stderr:

    logger.log(30, 'Test 1')  # This is saved to file

_add_stream_handler()
with open('out.txt', 'w') as sys.stderr:

    logger.log(30, 'Test 1')  # This is saved to file
    ag_logger.log(30, 'Test 2')  # This is also saved to file
    print(ag_logger.handlers)  # [<StreamHandler out.txt (NOTSET)>]
```

So when creating a handler for the logger `stream_handler = logging.StreamHandler()`, the default is `stderr`.
Somehow the first `with` altered sys.stderr context even when we are out of it, and the creation of `stream_handler` ended up creating a stream to `out.txt`.

This is a tricky solution here as we need to create a logger and handler ourselves to avoid alter root logger. However, the fact that it streams to `stderr` is not something can be easily changed unless we do `StreamHanlder.setStream()`. But the problem is when do we do it? It's weird that the `stderr` redirect context doesn't affect the `stream_handler` even when it's set to output to `stderr`

**Comment by 2-5** [comment]
In `autogluon-0.5.2`, I used the following code to capture the log output and send it to a file, while still letting it appear in the terminal:

```python
import logging

def logging_init(log_path):
    formatter = logging.Formatter(
        "{asctime}.{msecs:03.0f} {levelname:8} {name:64} {message}",
        datefmt="%H:%M:%S",
        style="{",
    )

    file_handler = logging.FileHandler(log_path)
    file_handler.setFormatter(formatter)

    root_logger = logging.getLogger()
    root_logger.addHandler(file_handler)
    root_logger.setLevel(logging.INFO)

# ...

def train():
    logging_init("train.log")
    # ...

```

This stopped working in `autogluon-0.6.0`, due to the logging changes, in particular `_logger_ag.propagate = False`

To be able to capture logging output to a file again, I needed to add this code:

```python
from autogluon.common.utils import log_utils

def logging_init(log_path):
    # ...
    log_utils._logger_ag.propagate = True
```

This solved my problem, but while searching the issues here to see if it was reported, I found this one and thought to add to it.

I think it's a bit weird that you disable log propagation, since in a way you are overriding higher level decisions. It took me quite a while to figure this one out, basically I searched for all logging related commits since `0.5.2` and found the refactor. Maybe it would be a good idea to document this special logging behaviour.

**Comment by yinweisu** [comment]
So if we don't set `propagate` as `False`, duplicated logs will be generated and the log format will vary between the duplications as the root logger has a different formatter, and we don't want to modify the root logger as that can lead to unexpected behavior to the user.

In your case, instead of adding handler to `root_logger`, adding the handler to ag_logger should work

**Comment by 2-5** [comment]
I attach to the root logger to capture all log output, not just `autogluon`. For example `sklearn`:

```
13:19:06.314 Level 15 autogluon.tabular.models.knn.knn_model  Using sklearnex KNN backend...
13:19:06.315 INFO     root                                    sklearn.neighbors.KNeighborsClassifier.fit: running accelerated version on CPU
```
