### ISSUE TITLE
Different pytorch-lightning version ranges between autogluon.multimodal and autogluon.timeseries

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#2830]
Multimodal and TimeSeries have different version ranges of pytorch-lightning

Mulitmodal: https://github.com/autogluon/autogluon/blob/master/multimodal/setup.py#L40

"pytorch-lightning>=1.8.0,<1.10.0",

TimeSeries: https://github.com/autogluon/autogluon/blob/master/timeseries/setup.py#L33

"pytorch-lightning>=1.7.4,<1.9.0",

@sxjscience @canerturkmen Please see if we can align on a unified version range, and move the version range to `core/_setup_utils.py` to avoid code dupe.

**Comment by sxjscience** [comment]
@Innixma can you change `pytorch_lightning` to `pytorch-lightning` in https://github.com/autogluon/autogluon/pull/2829 ?  (Or I can submit another PR).

Regarding the version of pytorch-lightning, I'm not sure whether we can upgrade the lightning dependency in timeseries (since it depends on GluonTS also: ). The dependencies themselves are not conflicting, the common version set is `>=1.8.0, <1.9.0` so it's fine for now.

**Comment by sxjscience** [comment]
I think different sub-packages may need different versions of lightning (Lightning itself is moving really fast, and has some API changes). So putting to `_setup_utils` may not be a very good option.

**Comment by Innixma** [comment]
> I think different sub-packages may need different versions of lightning (Lightning itself is moving really fast, and has some API changes). So putting to `_setup_utils` may not be a very good option.

This begs the question of if we should be installing all submodules by default. The scenario a user would be using timeseries and multimodal in the same environment is probably close to non-existent, thoughts?

**Comment by Innixma** [comment]
@sxjscience 

> can you change pytorch_lightning to pytorch-lightning in https://github.com/autogluon/autogluon/pull/2829 ? (Or I can submit another PR).

Updated the PR to change the name to `pytorch-lightning`

**Comment by Innixma** [comment]
Resolved in #2858
