### ISSUE TITLE
Tabular: Add Trainer callback support

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#2947]
It would be useful to add callback support to the overall TabularPredictor process, for the purposes of custom logging or early stopping.

A simple option would be to trigger the callback function after every model training, with the callback having a view of the `AutoTrainer` object, and the ability to access its methods.

Since Trainer is not currently part of the public user-facing API, writing a custom callback function would require a lot of knowledge from the user unless we somehow simplified it.

**Comment by 2-5** [comment]
I tried implementing a custom trainer for this purpose, something along the lines:

```python
class EvaluateTrainer(AutoTrainer):

    def _log_model_stats(self, model: str) -> None:
        model: AbstractModel = self.load_model(model)

        try:
            proba_np = self._load_model_y_pred_proba_val(model.name)
        except FileNotFoundError:
            return

        logger.info("\t%s", _CONTEXT.get_valid_score_str(proba_np))

# ...

predictor = TabularPredictor(
    learner_kwargs=dict(trainer_type=EvaluateTrainer),
    # ...
)
```

The problems I encountered:

- You need to pass a class (not instance) as `trainer_type`, but you have no way to pass arguments for when it will be constructed. I had to resort to global variables (`_CONTEXT`).
- I failed to call `model.predict_proba` on the finished model with unseen data (not train, not valid). I got complains that some features do not match, due to the transforms. But I can't call `predictor.transform_features`. it complains that the predictor is not fit yet (obviously).
- So I had to resort to loading the existing valid data (`_load_model_y_pred_proba_val`).
- The trainer is serialized to `trainer.pkl`, if you add any large instance variables to it, like a `pd.DataFrame`, you can end up with gigabyte sized `trainer.pkl` and long save times (10 sec)
- The serialization raises another question - what will happen when trying to `load` the predictor if the trainer class is missing.

Ideally:
- allow passing either a trainer instance, or allow passing arguments for the constructor (`trainer_kwargs`).
- even better, create a `TrainCallback` kind of class which is not serialized and not required to be present at `load`
- the model passed to the callback is fully finished, you are able to call `predict_proba` on it with unseen data - basically something similar to calling `predictor.predict_proba` is possible. even better if you can call most methods, `feature_importance` in particular. allow passing already transformed data (`transform_features`) since the callback will be called for many models
- if it's a stacked model, make it reasonably efficient to call `predict_proba` - allow preloading models like `persist_models` does

My use case:
- after each model is fit, I want to call `predict_proba` so I can compute my custom scores on `valid` / `test` data, call `feature_importance` and maybe even signal to the trainer that the fitting should stop.

**Comment by Innixma** [comment]
@2-5 Thanks for giving it a try and noting the existing limitations, this will be very helpful when we look towards enabling the functionality in an easier way!

We can probably target this for v1.0. I think adding `trainer_kwargs` is very reasonable as a first step. The ability to pass in additional information such as `test_data` as part of the callback without slowing things down and while properly handling data preprocessing to ensure the test data is compatible will require some thoughtful design consideration.

**Comment by Innixma** [comment]
Callbacks have been added in #4327
