### ISSUE TITLE
ModuleNotFoundError: No module named 'autogluon.eda'

### ISSUE THREAD

**Issue by eromoe** [autogluon/autogluon#3009]
From docs
https://auto.gluon.ai/stable/tutorials/eda/autogluon.eda.model.html?highlight=importance#autogluon.eda.visualization.model.FeatureImportance

Got error 
```
----> 1 import autogluon.eda.analysis as eda
      2 import autogluon.eda.visualization as viz
      3 import autogluon.eda.auto as auto

ModuleNotFoundError: No module named 'autogluon.eda'
```

version is 0.7.0
```
from autogluon import version
version.__version__
```

**Comment by Innixma** [comment]
`autogluon.eda` is a separate install:

Try the following:

```
pip install autogluon.eda
```

**Comment by Innixma** [comment]
Please re-open in case the issue persists, thanks!

**Comment by Kartz1986** [comment]
I am facing issue with 

pip install autogluon.eda

Getting the following error.

Requirement already satisfied: wcwidth in e:\pythonproject\automl\venv\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=6.1.0->ipywidgets<9.0,>=7.7.1->autogluon.eda) (0.2.6)
Requirement already satisfied: executing>=1.2.0 in e:\pythonproject\automl\venv\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets<9.0,>=7.7.1->autogluon.eda) (1.2.0)
Requirement already satisfied: pure-eval in e:\pythonproject\automl\venv\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets<9.0,>=7.7.1->autogluon.eda) (0.2.2)
Requirement already satisfied: asttokens>=2.1.0 in e:\pythonproject\automl\venv\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets<9.0,>=7.7.1->autogluon.eda) (2.2.1)      
ERROR: Will not install to the user site because it will lack sys.path precedence to matplotlib in e:\pythonproject\automl\venv\lib\site-packages


Windows Version - 11
Python version - 3.10
