### ISSUE TITLE
Add option to disable caching of local models

### ISSUE THREAD

**Issue by shchur** [autogluon/autogluon#3136]
Currently, all predictions made by local models like ETS and Naive are saved to disk. While this saves time when predicting many times for the same item, it introduces an overhead if we only predict once; it also may cause the CloudPredictor to crash when it's invoked in a read-only directory.

Adding a flag for disabling caching would be helpful to avoid these problems.

**Comment by shchur** [comment]
#3214 disabled caching for local models, so this is not relevant anymore

**Comment by Alex-Wenner-FHR** [comment]
I am experiencing this issue when deploying a TS AG model to sagemaker endpoints, with a custom inference script. It seems to fail because of a read only file system.

`OSError: [Errno 30] Read-only file system: 'AutogluonModels'`

and the code trying to load this model artifact directory:
```python
TimeSeriesPredictor(cache_predictions=False, log_to_file=False).load(path="autogluon-model")
```

I tried to just use `TimeSeriesPredictor.load(path="...")` but this failed trying to invoke certain models, with the same error. The two arguments passed into the `TimeSeriesPredictor` class was an attempt to force it to readonly.

- I am using AG latest, so 1.1.1. 

- It was trained on python 3.11.10 and inferenced on 3.11.9 (patch mismatch)

However, I am usure as to how to make AG only read and not write. Let me know if more information is needed! Thank you!
@shchur

**Comment by Alex-Wenner-FHR** [comment]
@shchur apologies, I have fixed this by passing `model.predict(data, use_cache=False)` instead of passing the arguments into the `TimeSeriesPredictor` class itself! This can be closed, this resolved this issue!
