### ISSUE TITLE
Cannot create a validation set because all training time series are too short

### ISSUE THREAD

**Issue by polina-l-1** [autogluon/autogluon#3154]
### Discussed in https://github.com/autogluon/autogluon/discussions/3153

<div type='discussions-op-text'>

<sup>Originally posted by **polina-l-1** April 17, 2023</sup>
Hello!

I have an error message after execution of

predictor = TimeSeriesPredictor(prediction_length=1, target="Line_Total", ignore_time_index=True).fit(train_data)

"ValueError: Cannot create a validation set because all training time series are too short. At least some time series in train_data must have length >= 2 * prediction_length + 1 (at least 3) but the longest training series has length 1. Please decrease prediction_length, provide longer time series in train_data, or provide tuning_data."

Thanks!</div>

**Comment by shchur** [comment]
Hi, this means that the time series that you provided in `train_data` are too short. They need to have length at least `2 * prediction_length + 1` for the TimeSeriesPredictor to work. If only some time series are too short, you can try removing them from `train_data`.

**Comment by polina-l-1** [comment]
Hi, could you please explain some more and how to fix it. Why are they too short? I have used the same data with Fb Prophet and it worked ok. Not sure I can remove them for my task.

I have:
print(len(train_data))
print(train_data.num_items)
print(len(train_data.item_ids))

755
755
755

**Comment by shchur** [comment]
It seems that the dataset contains 755 time series that all have length 1. Most likely something went wrong when creating the dataset. Make sure that the `item_id` column provided at dataset creation contains the unique ID of each time series (if you only have 1 time series in the dataset, this column should contain the same value for all rows).

**Comment by polina-l-1** [comment]
Before split to train and test:
<html>
<body>


id | OrderDate | Line_Total
-- | -- | --
0 | 2014-06-01 | 108466.3
1 | 2014-06-02 | 229555.4
2 | 2014-06-03 | 143882.5
3 | 2014-06-04 | 289031.3
4 | 2014-06-05 | 126623.3
... | ... | ...
941 | 2016-12-28 | 126810.9
942 | 2016-12-29 | 197502.6
943 | 2016-12-30 | 81847.2
944 | 2016-12-31 | 91736.4
945 | 2017-01-01 | 183090.9

<p style="margin-bottom: 6px; margin-top: 6px; color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">946 rows × 3 columns</p>
</body>
</html>

And train_data after the split:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Polina/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Polina/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  |   | Line_Total
-- | -- | --
item_id | timestamp |  
380 | 6/16/2015 | 110630.4
886 | 11/3/2016 | 107454.6
131 | 10/10/2014 | 105042.6
629 | 2/20/2016 | 190849.5
169 | 11/17/2014 | 150126.9
... | ... | ...
205 | 12/23/2014 | 98315.8
53 | 7/24/2014 | 133048.6
295 | 3/23/2015 | 48012.2
725 | 5/26/2016 | 101076.2
817 | 8/26/2016 | 156773.3
755 rows ×   1 columns |   |  



</body>

</html>


I can provide you the full dataset, it's not confidential, if needed

**Comment by shchur** [comment]
The `id` column should contain the same value for all rows since your dataset contains a single time series.

<html>
<body>


id | OrderDate | Line_Total
-- | -- | --
0 | 2014-06-01 | 108466.3
0 | 2014-06-02 | 229555.4
0 | 2014-06-03 | 143882.5
0 | 2014-06-04 | 289031.3
0 | 2014-06-05 | 126623.3
... | ... | ...
0 | 2016-12-28 | 126810.9
0 | 2016-12-29 | 197502.6
0 | 2016-12-30 | 81847.2
0 | 2016-12-31 | 91736.4
0 | 2017-01-01 | 183090.9

<p style="margin-bottom: 6px; margin-top: 6px; color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">946 rows × 3 columns</p>
</body>
</html>

In the example that you shared you are telling the predictor to treat each row of the dataframe as a separate time series with length 1.

**Comment by polina-l-1** [comment]
Thanks very much!
It works now
