### ISSUE TITLE
Support Torch 2.0

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#3250]
Support Torch 2.0

**Comment by giswqs** [comment]
The autogluon conda-forage package v0.8.0 now supports Windows. However, installing autogluon will downgrade pytorch cuda to pytorch cpu. This is probably caused by the pytorch version pin in the recipe `pytorch >=1.9,<1.14`. If autogluon can support torch 2.0, then autogluon on Windows will also have GPU support. 

```bash
conda create -n ag python=3.10
conda activate ag
conda install -c conda-forge mamba
mamba install pytorch torchvision pytorch-cuda -c pytorch -c nvidia
mamba install -c conda-forge autogluon
```

![image](https://github.com/autogluon/autogluon/assets/5016453/88dfb739-c71b-4d47-8a83-dc77bdafc4e7)

**Comment by Innixma** [comment]
Added Torch 2.0 support to AutoGluon v1.0
