### ISSUE TITLE
[Tabular] Improve path logic

### ISSUE THREAD

**Issue by yinweisu** [autogluon/autogluon#3260]
Currently path are stored as pure string, and `+` operations are used. This can easily lead to issue when dealing cross-os usage.

We would want to
1. Refactor to use `Pathlib.Path` in most of the places (at least in the core area)
2. Consider switching to a logic to store paths in a cascade manner, where a parent store both its path and its children's paths relative to its own path. And whenever a model creates / load its child, it passes the correct path to the child.

**Comment by Innixma** [comment]
Additionally:

- [ ] Delete StackerEnsembleModel, move logic into `AbstractTrainer`: Trainer should be the class to prepare the input and know the connections of the stacker models, because it is the object that stores the DAG of model connections. This should resolve the lions share of the path bugs.

**Comment by Innixma** [comment]
Related: #3325

**Comment by Innixma** [comment]
Related: #3318
