### ISSUE TITLE
[BUG Unable to Load TimeSeriesPredictor in AutoGluon

### ISSUE THREAD

**Issue by obwohl** [autogluon/autogluon#3524]
Description:
I successfully trained a TimeSeriesPredictor with AutoGluon and saved it. When I attempted to load the predictor the next day using the same environment and Jupyter Notebook, I encountered an issue. Initially, a version mismatch warning was shown, suggesting that the predictor was created in a version <=0.7.0, even though I was using version 0.8.2. When I bypassed the version check using require_version_match=False, a FileNotFoundError was raised, indicating it couldn't find predictor.pkl in the specified directory.

What's puzzling is that the predictor and its multiple model files were loaded successfully just a day ago.

Steps to Reproduce:

Train a TimeSeriesPredictor on version 0.8.2 of AutoGluon.
Save the predictor.
Attempt to load the predictor the following day.
Expected Behavior:
The predictor should be loaded without any issues, especially when no changes have been made to the environment or the directory.

Actual Behavior:
Received a version mismatch warning followed by a FileNotFoundError when trying to bypass the version check.

Environment:

AutoGluon version: 0.8.2
Python version: 3.10 (as observed from the traceback)
Operating System: MacOS
Additional Information:
I am using Jupyter Notebook, and I've verified that the working directory is correct. The models are stored under "AutogluonModels/2023-09-12 20:48Pr96Val5Win5Qhigh_quality", and each model seems to be in its respective subdirectory. The predictor.pkl was never directly in the main folder but inside subfolders.

**Comment by shchur** [comment]
Thank you for opening the issue! Do you think it would be feasible to provide a minimal working example for reproducing this issue + the traceback? Otherwise, debugging this issue would be problematic (and I'm not sure how to verify that the files were not modified externally, which could corrupt the saved predictor).

I would recommend training another predictor in a different directory and comparing the files to the original directory. Another potential source of the problem might be that the code for training predictor with the same path has been executed multiple times, which led to overwriting the contents of the saved predictor folder.

**Comment by obwohl** [comment]
It seems it was a problem within my env. Now I have to retrain in a new env but now PatchTST and DeepAR are not working anymore and I wasn't able to fix that for 2 hours. I'll wait for a version of ag which supports python 3.11 probably since right now the installation is very confusing.

**Comment by PurvaG1700** [comment]
Similar issues were discovered with Autogkuon 1.1.1. The load() method throws an error saying the model was saved with different version
