### ISSUE TITLE
GradCam Implementation

### ISSUE THREAD

**Issue by ebrunvrz** [autogluon/autogluon#3561]
I am using a MultiModal predictor to do binaryclassification. I trained my model and load it back to reach forward and backward I am using this commands:

predictor = MultiModalPredictor.load(path)
predictor._model.forward(input_tensor)

However I am getting an error like this:
TypeError: TimmAutoModelForImagePrediction.forward() missing 1 required positional argument: 'image_valid_num'

When I search for image_valid_num I only could find this command predictor._model.image_valid_num_key which returns this as string:
'timm_image_image_valid_num'

My question is how can I find what is this image valid num and where can I find in my saved model?

**Comment by FANGAreNotGnu** [comment]
Here is an example to get the image_valid_num from processed input batch (dict of tensors): https://github.com/autogluon/autogluon/blob/bf4940ee3d9a20e2d99015aa62afd18e493d3c5a/multimodal/src/autogluon/multimodal/models/clip.py#L141 during training The image_valid_num for each data entry is computed here: https://github.com/autogluon/autogluon/blob/bf4940ee3d9a20e2d99015aa62afd18e493d3c5a/multimodal/src/autogluon/multimodal/data/process_image.py#L306 and collated as a tensor here: https://github.com/autogluon/autogluon/blob/bf4940ee3d9a20e2d99015aa62afd18e493d3c5a/multimodal/src/autogluon/multimodal/data/process_image.py#L179 This is the forward function you called: https://github.com/autogluon/autogluon/blob/bf4940ee3d9a20e2d99015aa62afd18e493d3c5a/multimodal/src/autogluon/multimodal/models/timm_image.py#L132 The root cause seems to be that the data is not preprocessed.
