### ISSUE TITLE
Fix Broken Links on Website

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#3603]
Fix all broken links listed here:

https://github.com/autogluon/autogluon-brokenlinks/blob/master/Broken%20Links%20Dev.csv

- #3604 resolves several of them, primarily for Tabular module.
- #3607 resolves the broken links in the whats_new files.

**Comment by LennartPurucker** [comment]
Heyho, it seems a few new dead links appeared in the documentation (e.g., [here](https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-custom-metric.html) instead of [this](https://auto.gluon.ai/stable/tutorials/tabular/advanced/tabular-custom-metric.html)) with an access denied response.

**Comment by tonyhoo** [comment]
All broken links have been fixed as part of 1.2 release. Resolving
