### ISSUE TITLE
Add support for PyTorch 2.1

### ISSUE THREAD

**Issue by shchur** [autogluon/autogluon#3613]
Should we increase the dependency ranges in [`_setup_utils.py`](https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py) to `torch>=2.0,<2.2` and, potentially, `lightning>=2.0,<2.2` in the AutoGluon v1.0 release?

To do:
- [ ] #3708
- [ ] #3827

@zhiqiangdon @tonyhoo @Innixma

**Comment by stevenmanton** [comment]
I'm interested in this. We want to use torch 2.1 but cannot alongside AutuGluon. The 2.1 restriction seems a bit too stringent. Was this done out of an abundance of caution or is there a known incompatibility?

**Comment by Ludecan** [comment]
It would be awesome if you guys could pull this out. 
I'm having issues with Neural Net models because of a bug in torch==2.0.1 (the one that gets installed by default with AutoGluon==1.0.0).
Apparently torch didn't install the required CUDA libraries needed to work and it was fixed in 2.1.1:
https://github.com/pytorch/pytorch/issues/100974

Is there any way to manually install these?

Attached is the error log I'm getting
[error.txt](https://github.com/autogluon/autogluon/files/14547111/error.txt)
