### ISSUE TITLE
[BUG] Update statsforecast range to support pandas 2.0 for ARIMA

### ISSUE THREAD

**Issue by drewbitt** [autogluon/autogluon#4035]
Although seemingly everything autogluon uses in `statsforecast` is pandas 2.0 compatible considering `1.0` was supposed to be pandas 2.0 compatible, statsforecast ARIMA was not pandas 2.0 compatible until https://github.com/Nixtla/statsforecast/pull/456 which landed in 1.6.0. autogluon forces <=1.5.0 https://github.com/autogluon/autogluon/blob/d7a9b98b5061da419bb177b16a2a7ee4903b15aa/timeseries/setup.py#L37

I don't think we are directly effected since it appears AutoArima through autogluon does work. But, usage of statsforecast for additional ARIMA code can error with `TypeError: concat() takes 1 positional argument but 2 were given` in environments where autogluon and statsforecast are both used.

**Comment by shchur** [comment]
Hi @drewbitt, thank you for the suggestion. Unfortunately, we are currently blocked from upgrading StatsForecast beyond 1.5.0 because of its dependency clash with OmegaConf (see #3458 for details). The release of `fugue-0.9.0` (https://github.com/fugue-project/fugue/issues/509) should resolve this issue.
