### ISSUE TITLE
[BUG] Error crash Ray Dashboard On Kaggle Notebook (Preset : best_quality_hpo)

### ISSUE THREAD

**Issue by rizal-mujahiddan69** [autogluon/autogluon#4057]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [x] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

Why while running image prediction, stopped and get error when using best_quality_hpo in parameter presets? 
(  **Im using Kaggle note book** )

**Expected behavior**

Not Error

**Screenshots / Logs**
![image](https://github.com/autogluon/autogluon/assets/86094348/e68ee85e-16bb-4c84-a566-c64839b46c6f)

**Installed Versions**

1.0.0 (Newest)

</details>

**Comment by suzhoum** [comment]
@rizal-mujahiddan69 I was able to reproduce the error for `AutoGluon==1.0.0` in Kaggle Notebook. I believe it errors out at `ray.init()` due to some incompatibility between `grpcio` AutoGluon installed and the Notebook's pre-existing environment. Upgrading to `grpcio==1.68.0` seems to resolve the issue. 

FYI, this issue doesn't happen on AutoGluon 1.1.1. We encourage you to try our latest version to enjoy the best support.
