### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by psmoros** [autogluon/autogluon#4191]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@yuligesec) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by psmoros** [comment]
Sent a magic link to innixma@gmail.com :) Let me know if that works

**Comment by Innixma** [comment]
Hi @psmoros, I received your email and responded, thanks! I'll re-open this issue since we have not yet created the SECURITY.md file, and I think it would be a good idea for us to do so.

Note to team: We can base the file off of sklearn's: https://github.com/scikit-learn/scikit-learn/blob/main/SECURITY.md
