### ISSUE TITLE
[timeseries] When saving predictor to a folder with an existing predictor, delete the old predictor

### ISSUE THREAD

**Issue by shchur** [autogluon/autogluon#4195]
## Description
- When the user sets `TimeSeriesPredictor(path="folder/with/existing/predictor")`, a lot of weird undocumented behaviors may occur (e.g., #4150). We currently log a warning in this case, but it's often ignored by the users, leading to confusion. A cleaner option would be to delete all the files related to the old predictor.

**Comment by Innixma** [comment]
Note that for Tabular, I don't delete the old files, but I believe the logic still works correctly without bugs in this case.

I'd lean towards trying to fix the bugs rather than brute-force deleting the old files. For instance, what if the pre-existing files aren't related to AutoGluon?

I'd be curious what the reason behind some of the bugs are. I expect it has to do with searching for the existence of files altering the logic in TimeSeries.

**Comment by shchur** [comment]
#4202 was sufficient to fix problems with loading
