### ISSUE TITLE
Multiple frequency for TimeSeriesPredictor

### ISSUE THREAD

**Issue by Mhdaw** [autogluon/autogluon#4743]
Hello all,
Is it possible to train the TimeSeriesPredictor on a data set with multiple freq?
if so how? If not, How can we approach such matter

**Comment by shchur** [comment]
Hi @Mhdaw, this is currently not supported because some models (e.g., DeepAR, ETS) have different # of parameters depending on the frequency of the data.

There are two options:
1. Replace the timestamps in all of the time series with a dummy frequency (e.g., daily or hourly) and train a single model on all of them.
2. Train a separate model for each frequency.

It's hard to tell in advance which strategy will result in best forecast accuracy - I recommend that you try out both.

**Comment by Mhdaw** [comment]
@shchur Thank you for your fast response,
since Chronos models don't use the time feature as an input to the model and treat the data as a simple sequence, Can I replace all timestamps with the lowest frequency on the dataset?
And I will also try a separate model for each frequency

**Comment by shchur** [comment]
Yes, if you only use the Chronos model, replacing all timestamps with arbitrary values will work.

**Comment by Mhdaw** [comment]
Thanks

**Comment by Mhdaw** [comment]
Thanks
