### ISSUE TITLE
Apply black

### ISSUE THREAD

**Issue by daikikatsuragawa** [autogluon/autogluon#798]
I propose the introduction of black code formatter in order to create an environment that is easy to deal with other problems.

https://github.com/psf/black

For example, in the following, `”` and `’` of (A) will be unified.

(A)

```python
if y_type not in ["binary", "multiclass", 'multilabel-indicator']:
```

https://github.com/awslabs/autogluon/blob/master/core/src/autogluon/core/metrics/classification_metrics.py#L19

**Comment by Innixma** [comment]
Pretty cool tool! How would you generally incorporate this into a project? Would it be a CI check on PRs to check that it satisfies black guidelines? I'd assume a large refactor PR to apply black guidelines followed by a CI check would be the most practical method.

**Comment by daikikatsuragawa** [comment]
@Innixma 

Sorry for the late reply.

Below are some ideas. What do you think?
I would like to discuss, share opinions, and brush up.

- Apply Black for the time being, then put a badge on the README to encourage contributors to use Black. And added to [Tips for Modifying the Source Code](Tips for Modifying the Source Code)
  - Sample: https://github.com/stanfordmlgroup/ngboost

- Similar to CodeQL, the result of Black is shown as the result of GitHub Action. After that, the contributor who was warned by Black commits additionally.

- If Black is not adapted, CI automatically adapts Black and commits. (At the time of pull request)
  - Sample: https://github.com/nostalgia-dev/nostalgia/blob/master/.github/workflows/apply-black.yml

**Comment by daikikatsuragawa** [comment]
https://github.com/awslabs/aws-data-wrangler/blob/main/.github/workflows/static-checking.yml

**Comment by Innixma** [comment]
Thanks for the breakdown!

I think as a first step, doing the first option would be most pragmatic to get the majority of benefits. I'd be open to adding a GitHub Action in future so long as it doesn't distract contributors efforts (If we just do a Black application every couple of months, we wouldn't need our contributors to worry about adhering to it so strictly). Automatic adaptation could be considered, but it sounds like something that would need a bit of testing and effort to setup initially.

I think anything beyond the manual black apply should wait until mid-Feb once v0.1 has been released, just in the off-chance that it impacts anything in a strange manner (likely not, but AG has a lot of moving parts which can't all be verified by our tests and CI, so I'd rather be safe than sorry for a major release).

We'd also want to have some file which indicates our Black settings, since we would want longer max line lengths than typical.

**Comment by daikikatsuragawa** [comment]
Thank you for your reply!
I agree with that opinion!

**Comment by daikikatsuragawa** [comment]
For reference, I tried it after forking.

https://github.com/daikikatsuragawa/autogluon/commit/35d81213ac914999003844bf1d8ac48eeb9a5897

The settings are as follows:

https://github.com/daikikatsuragawa/autogluon/blob/black/pyproject.toml

If there seems to be no problem, I would like to send you a pull request.

**Comment by Innixma** [comment]
It looks reasonable to me, although I'd suggest we have a longer line limit since we want to incentivize descriptive variables.

I would be in favor of a line-limit of **160** or 180, although it seems 160 is the length used by GitHub.

Outside of line limit, I notice `black` is doing a few strange things related to long strings:

[Example](https://github.com/daikikatsuragawa/autogluon/blob/35d81213ac914999003844bf1d8ac48eeb9a5897/tabular/src/autogluon/tabular/trainer/abstract_trainer.py#L1763) : Ideally we would want to keep this as 1 line instead of breaking it into 3 since even after breaking it into 3 it is still over the line limit.

There are also cases of [same-line comments](https://github.com/daikikatsuragawa/autogluon/blob/35d81213ac914999003844bf1d8ac48eeb9a5897/tabular/src/autogluon/tabular/trainer/abstract_trainer.py#L105) causing wrapping in an ugly fashion.

I'm ok with accepting these formatting oddities for the sake of consistency, but this will definitely cause a lot of rebasing difficulties for in-progress work leading up to v0.1 release. Because of this, I think it makes sense to wait on this PR until we are v0.1 release ready or until after v0.1 release (v0.1 release is planned for Feb 8th, and we'd want to be release ready at least by ~Feb 4th)


@gradientsky @jwmueller @zhreshold @sxjscience feel free to weigh in. In particular, I'm curious about the teams opinions on:

1. Using `black`
2. Line Limit
3. Timeline for `black` application PR: Updates virtually every file in the codebase. Main question is if we do this before or after `v0.1`.

**Comment by sxjscience** [comment]
Since Black won't change the API and just enhances the coding format, I will prefer adopting it after v0.1.

**Comment by daikikatsuragawa** [comment]
Send a pull request as needed.
What kind of timing is good?

**Comment by Innixma** [comment]
Hi @daikikatsuragawa,

Thanks for the follow-up! I think in ~2 weeks we should be in a good spot for the PR. v0.2 release is planned in ~1-2 weeks, so we will try to get that released and then directly follow-up with the `apply black` PR. I might also try to apply black to a few of the submodules individually before then to minimize the blast radius. The tricky part is we have collaborators / devs working on each of the submodules at the same time, so per-module refactors will likely be less disruptive.

**Comment by gradientsky** [comment]
[EDA package](https://github.com/awslabs/autogluon/tree/master/eda) has full integration with `tox` incliding `typecheck`, `lint` and `format` targets. I suggest the same approach is used in other modules. 
Test scripts already migrated [here](https://github.com/awslabs/autogluon/blob/master/.github/workflow_scripts/test_eda.sh#L17-L20).

**Comment by yinweisu** [comment]
We should probably consider a short code freeze and applying black after the 0.8 release so we can avoid doing it prior 1.0 release

**Comment by Innixma** [comment]
All packages are now using black formatting!
